# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: YohanesOkta.StageManager
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: Yohanes Oktanio
PublisherUrl: https://github.com/yohanesokta
PublisherSupportUrl: https://github.com/yohanesokta/stage-manager/issues
PackageName: Stage Manager
PackageUrl: https://github.com/yohanesokta/stage-manager
License: MIT
LicenseUrl: https://github.com/yohanesokta/stage-manager
ShortDescription: macOS Stage Manager experience for Windows.
Description: |
  Stage Manager for Windows brings the desktop windowing and staging experience to Windows,
  keeping the active app front and center while organizing background apps into a dynamic shelf.
Moniker: stagemanager
Tags:
- desktop
- productivity
- stage-manager
- window-manager
ReleaseNotesUrl: https://github.com/yohanesokta/stage-manager/releases/tag/v1.0.0
ManifestType: defaultLocale
ManifestVersion: 1.6.0
